fullName: gateway-igs
service:
  type: ClusterIP
  ports:
    http: 8080
istio:
  virtualService:
    gateways: {}
    http:
      match:
        - headers:
            gateway-request:
              exact: "true"
          uri:
            prefix: /gateway/igs
      rewrite:
        uri: /
      retries:
        enable: false
        retryOn: null
      timeout: null
    hosts: {}
  subsets:
    main:
      version: 1.0.0
      weight: "100"
# activate Traffic mirroring, also called shadowing with the following lines
#      mirror:
#        version: 1.1.0
#        mirrorPercentage: 0
